name: meditation
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # firebase
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+4
  google_sign_in: ^4.0.1+1

  # ios
  cupertino_icons: ^0.1.2

  # font
  font_awesome_flutter: ^8.5.0

  # pattern
  bloc: ^0.15.0
  flutter_bloc: ^0.21.0

  # shared_preferences
  shared_preferences: ^0.5.3+4

  # line auth
  flutter_line_login: ^0.2.0 
  #//error kotlin 2 

  # player sound
  
  # other
  wave: ^0.0.8
  equatable: ^0.2.0
  meta: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 400  