name: meditation
description: A new Flutter application.

version: 1.0.1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # language
  flutter_i18n: ^0.13.2

  # firebase
  firebase_core: ^0.4.2
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.10+2
  
  # icon
    # ios 
  cupertino_icons: ^0.1.2
    # font
  font_awesome_flutter: ^8.5.0

  # storage management
  shared_preferences: ^0.5.3+4
  path_provider: ^1.6.5

  # google auth
  google_sign_in: ^4.0.14

  # player sound
  audio_service: ^0.8.0
  sys_volume: ^0.1.0
  just_audio: ^0.1.8

  # date
  intl: ^0.16.0
  # share
  share: ^0.6.4   
  # vibration
  vibration: ^1.2.4

  # UI
    # welcome intro slider
  intro_slider: ^2.2.9
    # splash screen
  splashscreen: ^1.2.0
    # popup loading
  progress_dialog: ^1.2.2
    # animation 2d
  flare_flutter: ^2.0.3
    # rating bar
  flutter_rating_bar: ^3.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # line auth
  #flutter_line_login: 
    #path: ./vender/flutter_line_login/
    
flutter:
  uses-material-design: true

  assets:
    - assets/animation/
    - assets/images/
    - assets/languages/
  fonts:
    - family: Prompt
      fonts:
        - asset: assets/fonts/Prompt/Prompt-Regular.ttf
        - asset: assets/fonts/Prompt/Prompt-Italic.ttf
          style: italic
        - asset: assets/fonts/Prompt/Prompt-Light.ttf 
          weight: 200
        - asset: assets/fonts/Prompt/Prompt-LightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Prompt/Prompt-Medium.ttf
          weight: 300
        - asset: assets/fonts/Prompt/Prompt-MediumItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Prompt/Prompt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Prompt/Prompt-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Prompt/Prompt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Prompt/Prompt-BoldItalic.ttf
          weight: 700
          style: italic