name: meditation
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # firebase
  firebase_core: ^0.4.2
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.10+2

  # ios
  cupertino_icons: ^0.1.2

  # font
  font_awesome_flutter: ^8.5.0

  # pattern
  flutter_bloc: ^2.0.1

  # shared_preferences
  shared_preferences: ^0.5.3+4

  # facebook auth
  flutter_facebook_login: ^3.0.0

  # google auth
  google_sign_in: ^4.0.14

  # player sound
  
  # other
  wave: ^0.0.8
  equatable: ^0.6.0
  meta: ^1.1.6
  smooth_star_rating: ^1.0.3
  intl: ^0.16.0
  http:

dev_dependencies:
  flutter_test:
    sdk: flutter
  # line auth
  flutter_line_login: 
    #path: ./vender/flutter_line_login/
    
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fitness_app/

  fonts:
    - family: Prompt
      fonts:
        - asset: assets\fonts\Prompt\Prompt-Regular.ttf
        - asset: assets\fonts\Prompt\Prompt-Italic.ttf
          style: italic
        - asset: assets\fonts\Prompt\Prompt-Light.ttf
          weight: 200
        - asset: assets\fonts\Prompt\Prompt-LightItalic.ttf
          weight: 200
          style: italic
        - asset: assets\fonts\Prompt\Prompt-Medium.ttf
          weight: 300
        - asset: assets\fonts\Prompt\Prompt-MediumItalic.ttf
          weight: 300
          style: italic
        - asset: assets\fonts\Prompt\Prompt-SemiBold.ttf
          weight: 600
        - asset: assets\fonts\Prompt\Prompt-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets\fonts\Prompt\Prompt-Bold.ttf
          weight: 700
        - asset: assets\fonts\Prompt\Prompt-BoldItalic.ttf
          weight: 700
          style: italic